### ISSUE TITLE
Almanac: Knowledge-Grounded Language Models for Clinical Medicine

### ISSUE THREAD

**Issue by cyrilzakka** [lucidrains/medical-chatgpt#4]
Hey @lucidrains, just wanted to bring your attention to our preprint: https://arxiv.org/abs/2303.01229 where we ground an LLM in various medical websites, calculators etc, resulting in more accurate outputs. We're working on a full manuscript and will release more results soon!

**Comment by lucidrains** [comment]
oh hey Cyril, glad to see that you've finished medical school and even found your way to the bay area

yea, would be happy to check out your model. do you plan on putting it on huggingface?

**Comment by lucidrains** [comment]
yea, shoot me an email with the deets once you are ready

i have my own plans for this repo
